services:
  - type: web
    name: todo-backend
    env: node
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_HOST
        fromDatabase:
          name: todo-database
          property: host
      - key: DB_PORT
        fromDatabase:
          name: todo-database
          property: port
      - key: DB_NAME
        fromDatabase:
          name: todo-database
          property: database
      - key: DB_USER
        fromDatabase:
          name: todo-database
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: todo-database
          property: password

  - type: web
    name: todo-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://todo-backend.onrender.com/api

databases:
  - name: todo-database
    databaseName: todo_db
    user: todo_user
